export const GAMIFICATION_POINTS = {
  GOAL_COMPLETE: 10,
  STREAK_7: 50,
  STREAK_30: 200,
  STREAK_100: 500,
  LEARNING_ENTRY: 15,
  RESOURCE_COMPLETED: 100,
  SKILL_FOCUS_COMPLETED: 75,
  OUTREACH_ACTIVITY: 5,
  OUTREACH_GOAL_COMPLETE: 60,
} as const;

export const STREAK_MILESTONES = [7, 30, 100] as const;

export const POINTS_PER_LEVEL = 500;
